import 'dotenv/config';
import { db } from './src/db/index.js';
import { blogs } from './src/db/schema.js';
import { v4 as uuid } from 'uuid';

const MORE_BLOGS = [
  {
    title: 'GraphQL vs REST: Choosing the Right API',
    description: 'A practical comparison of GraphQL and REST — when to use each and how to migrate between them.',
    image: 'https://images.unsplash.com/photo-1484417894907-623942c8ee29?w=800&q=80',
    content: '<p>GraphQL and REST are both valid API approaches...</p>',
    category: 'Backend',
    tags: ['GraphQL', 'REST', 'API'],
    authorName: 'Adaeze Okonkwo',
    authorImage: 'https://i.pravatar.cc/150?img=47',
    authorBio: 'Senior Backend Engineer',
    minsRead: 13, featured: false, status: 'published', views: 4560, likes: 334,
  },
  {
    title: 'CSS Grid vs Flexbox: When to Use Which',
    description: 'A definitive guide to choosing between CSS Grid and Flexbox with real-world examples.',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80',
    content: '<p>Choosing between CSS Grid and Flexbox is a question every developer faces...</p>',
    category: 'Frontend',
    tags: ['CSS', 'Grid', 'Flexbox'],
    authorName: 'Chidi Eze',
    authorImage: 'https://i.pravatar.cc/150?img=33',
    authorBio: 'Frontend Architect',
    minsRead: 7, featured: false, status: 'published', views: 3200, likes: 245,
  },
  {
    title: 'Monitoring Node.js Apps with Prometheus and Grafana',
    description: 'Set up production-grade observability for your Node.js services.',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80',
    content: '<p>Observability is the backbone of reliable production systems...</p>',
    category: 'DevOps',
    tags: ['Monitoring', 'Prometheus', 'Grafana'],
    authorName: 'Olumide Adeyemi',
    authorImage: 'https://i.pravatar.cc/150?img=51',
    authorBio: 'Database Architect',
    minsRead: 14, featured: false, status: 'published', views: 1987, likes: 156,
  },
  {
    title: 'Designing Accessible Web Applications',
    description: 'Learn WCAG guidelines, ARIA roles, and keyboard navigation patterns that work.',
    image: 'https://images.unsplash.com/photo-1559028012-481c04fa702d?w=800&q=80',
    content: '<p>Web accessibility ensures everyone can use your application...</p>',
    category: 'Design',
    tags: ['Accessibility', 'WCAG', 'UX'],
    authorName: 'Sade Adewale',
    authorImage: 'https://i.pravatar.cc/150?img=56',
    authorBio: 'UI/UX Designer',
    minsRead: 9, featured: false, status: 'published', views: 2340, likes: 178,
  },
  {
    title: 'Building Real-Time Apps with WebSockets',
    description: 'Learn how to build real-time features like chat, notifications and live updates.',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80',
    content: '<p>Real-time communication has become essential in modern web apps...</p>',
    category: 'Backend',
    tags: ['WebSockets', 'Node.js', 'Real-time'],
    authorName: 'Adaeze Okonkwo',
    authorImage: 'https://i.pravatar.cc/150?img=47',
    authorBio: 'Senior Backend Engineer',
    minsRead: 11, featured: false, status: 'published', views: 3100, likes: 220,
  },
  {
    title: 'Next.js 14 App Router: Complete Guide',
    description: 'Everything you need to know about the Next.js App Router and server components.',
    image: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800&q=80',
    content: '<p>Next.js 14 introduces major improvements to the App Router...</p>',
    category: 'Frontend',
    tags: ['Next.js', 'React', 'SSR'],
    authorName: 'Ngozi Osei',
    authorImage: 'https://i.pravatar.cc/150?img=38',
    authorBio: 'React Specialist',
    minsRead: 12, featured: false, status: 'published', views: 6800, likes: 510,
  },
  {
    title: 'Database Migrations Best Practices',
    description: 'How to safely run database migrations in production without downtime.',
    image: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=800&q=80',
    content: '<p>Database migrations are one of the riskiest operations in production...</p>',
    category: 'Database',
    tags: ['PostgreSQL', 'Migrations', 'DevOps'],
    authorName: 'Olumide Adeyemi',
    authorImage: 'https://i.pravatar.cc/150?img=51',
    authorBio: 'Database Architect',
    minsRead: 10, featured: false, status: 'published', views: 2900, likes: 198,
  },
  {
    title: 'CI/CD Pipeline with GitHub Actions',
    description: 'Build a complete CI/CD pipeline for your Node.js app using GitHub Actions.',
    image: 'https://images.unsplash.com/photo-1518432031352-d6fc5c10da5a?w=800&q=80',
    content: '<p>A good CI/CD pipeline is essential for shipping code confidently...</p>',
    category: 'DevOps',
    tags: ['GitHub Actions', 'CI/CD', 'DevOps'],
    authorName: 'Olumide Adeyemi',
    authorImage: 'https://i.pravatar.cc/150?img=51',
    authorBio: 'Database Architect',
    minsRead: 8, featured: false, status: 'published', views: 2200, likes: 167,
  },
  {
    title: 'React Query vs Redux Toolkit',
    description: 'When to use React Query and when to stick with Redux Toolkit for state management.',
    image: 'https://images.unsplash.com/photo-1507721999472-8ed4421c4af2?w=800&q=80',
    content: '<p>Choosing the right state management solution is critical...</p>',
    category: 'Frontend',
    tags: ['React', 'Redux', 'State Management'],
    authorName: 'Chidi Eze',
    authorImage: 'https://i.pravatar.cc/150?img=33',
    authorBio: 'Frontend Architect',
    minsRead: 9, featured: false, status: 'published', views: 4100, likes: 301,
  },
  {
    title: 'Building a Vector Search Engine with pgvector',
    description: 'Add AI-powered semantic search to your PostgreSQL database using pgvector.',
    image: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&q=80',
    content: '<p>Vector search is transforming how we build search features...</p>',
    category: 'AI & ML',
    tags: ['PostgreSQL', 'pgvector', 'AI', 'Search'],
    authorName: 'Ngozi Osei',
    authorImage: 'https://i.pravatar.cc/150?img=38',
    authorBio: 'React Specialist',
    minsRead: 15, featured: false, status: 'published', views: 5400, likes: 412,
  },
  {
    title: 'Micro-Frontends with Module Federation',
    description: 'Split your large frontend into independent deployable micro-frontends.',
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&q=80',
    content: '<p>Micro-frontends bring microservice thinking to the frontend...</p>',
    category: 'Frontend',
    tags: ['Webpack', 'Module Federation', 'Architecture'],
    authorName: 'Chidi Eze',
    authorImage: 'https://i.pravatar.cc/150?img=33',
    authorBio: 'Frontend Architect',
    minsRead: 14, featured: false, status: 'published', views: 2700, likes: 189,
  },
  {
    title: 'Securing Node.js APIs: JWT and Rate Limiting',
    description: 'Best practices for securing your Node.js APIs with JWT authentication and rate limiting.',
    image: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&q=80',
    content: '<p>Security should never be an afterthought in API development...</p>',
    category: 'Backend',
    tags: ['Security', 'JWT', 'Node.js'],
    authorName: 'Adaeze Okonkwo',
    authorImage: 'https://i.pravatar.cc/150?img=47',
    authorBio: 'Senior Backend Engineer',
    minsRead: 10, featured: false, status: 'published', views: 3800, likes: 287,
  },
];

async function addMore() {
  console.log('Adding more blogs...');
  for (const blog of MORE_BLOGS) {
    await db.insert(blogs).values({
      id:          uuid(),
      ...blog,
      tags:        blog.tags,
      publishedAt: new Date(),
      createdAt:   new Date(),
      updatedAt:   new Date(),
    });
    console.log(`  ✅ ${blog.title}`);
  }
  console.log('\n✨ Done! Added ' + MORE_BLOGS.length + ' more blogs.');
  process.exit(0);
}

addMore().catch(e => { console.error(e); process.exit(1); });